version: '3'
services:
    prometheus-aeron:
        image: "prometheusaeron"
        command: >
            bash -c "java -cp /opt/aeron-prometheus-stats/lib/aeron-prometheus-stats-all-1.0-SNAPSHOT.jar\
             -Daeron.dir=/dev/shm/aeron co.fairtide.prometheus_aeron_stat.PrometheusAeronStat port=50051 delay=${DELAY_SECONDS}"
        ports:
        - "${PROMETHEUS_PORT}:50051"
        shm_size: 1G
        volumes:
        - ${DAERON_DIR}:/dev/shm/aeron/
